# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eellie <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/03/16 22:37:15 by eellie            #+#    #+#              #
#    Updated: 2020/03/17 16:22:20 by eellie           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op
SRCS = ft_oper.c ft_source.c do_op.c
HEADER = ft_h.h

all:
	gcc -o $(NAME) $(SRCS)

clean:
	/bin/rm -f $(NAME)

re: clean all
